ALTER TABLE live_sessions ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE live_sessions ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE live_sessions ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ;
